//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autorisations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permi
    {
        public string NDecision { get; set; }
        public string NomPrenom { get; set; }
        public string Autorisation { get; set; }
        public string Reference_Fonciers { get; set; }
        public Nullable<System.DateTime> pv { get; set; }
        public string typePermis { get; set; }
        public byte[] document { get; set; }
    }
}
